Repository maistra/istio-workspace, pull requests merged in 2020-11, with the labels that each got.

#558 fix(test-infra): updates github action commands in linter
  .github/workflows/golangci_lint.yml
Labels: internal/test-infra, kind/bug

#557 feat(build): introduces go modules
  .circleci/config.yml
  .github/workflows/golangci_lint.yml
  Gopkg.lock
  Gopkg.toml
  Makefile
  go.mod
  go.sum
  pkg/assets/isto-workspace-deploy.go
  pkg/cmd/config/config_suite_test.go
  pkg/cmd/create/create_suite_test.go
  pkg/cmd/delete/delete_suite_test.go
  pkg/cmd/develop/develop_suite_test.go
  pkg/cmd/internal/session/session_suite_test.go
  pkg/cmd/version/releases.go
  pkg/cmd/version/version_suite_test.go
  pkg/cmd/watch/watch_cmd_suite_test.go
  pkg/controller/session/session_suite_test.go
  pkg/internal/session/session_suite_test.go
  pkg/istio/istio_suite_test.go
  pkg/k8s/k8s_suite_test.go
  pkg/model/model_suite_test.go
  pkg/naming/k8s_naming_suite_test.go
  pkg/openshift/openshift_suite_test.go
  pkg/openshift/parser/parser_suite_test.go
  pkg/telepresence/telepresence_suite_test.go
  pkg/template/template_suite_test.go
  pkg/watch/watch_suite_test.go
  test/cmd/test-scenario/generator/generator_suite_test.go
  test/test_suite.tpl
  tools.go
Labels: internal/infra, kind/enhancement

#556 feat: add health and readiness endpoints + probe config
  deploy/operator.tpl.yaml
  pkg/cmd/serve/serve.go
  pkg/openshift/parser/template_test.go
Labels: component/operator, kind/enhancement

#562 fix(tests): template/yaml tests asserts against yaml not string
  go.mod
  go.sum
  pkg/assets/isto-workspace-deploy.go
  pkg/openshift/parser/template_test.go
  pkg/template/template_test.go
Labels: internal/test-infra, kind/enhancement

#571 feat(gh-action): cleans up pr images on pr close
  .github/workflows/cleanup_pr_images.yml
Labels: internal/test-infra, kind/enhancement

#564 feat: introduces new job for building and pushing images
  .circleci/config.yml
  .github/labels.yml
  .github/workflows/golangci_lint.yml
  Makefile
  e2e/e2e_suite_test.go
  e2e/infra/image_registry.go
  e2e/smoke_test.go
Labels: images-available

#572 fix(ci): uses `latest` tag for master image builds
  .circleci/config.yml
  .github/workflows/cleanup_pr_images.yml
Labels: internal/test-infra, kind/bug

#573 chore(circle): removes e2e tests job on daily
  .circleci/config.yml
Labels: internal/test-infra, kind/enhancement, skip-changelog

#574 chore: better names for gh actions
  .github/workflows/cleanup_pr_images.yml
  .github/workflows/golangci_lint.yml
  .github/workflows/release_tag.yml
Labels: internal/test-infra, kind/enhancement, skip-changelog

#560 feat(deps): updates to official dependabot v2
  .dependabot/config.yml
  .github/dependabot.yml
Labels: internal/infra, kind/enhancement

#585 chore(circleci): cleans up circleci jobs
  .circleci/config.yml
  .github/workflows/golangci_lint.yml
  .github/workflows/validate_circleci.yml
  .goreleaser.yml
Labels: internal/test-infra, kind/enhancement, skip-changelog
