Repository maistra/istio-workspace, pull requests merged in 2020-04, with the labels that each got.

#407 docs: fixes headers in release notes
  docs/modules/ROOT/pages/release_notes/release_notes_template.adoc
  docs/modules/ROOT/pages/release_notes/v0.0.2.adoc
  docs/modules/ROOT/pages/release_notes/v0.0.3.adoc
Labels: component/docs, kind/bug

#408 chore(ci): bumps golang to 1.14.1
  .circleci/config.yml
  pkg/assets/isto-workspace-deploy.go
  pkg/log/log.go
  test/cmd/test-service/html.go
Labels: internal/infra

#410 feat: ability to specify a file name when using get.sh
  README.adoc
  docs/modules/ROOT/pages/getting_started.adoc
  pkg/cmd/root.go
  scripts/get.sh
Labels: internal/infra, kind/enhancement

#415 lint(deprecated): updated packages runtime/scheme and runtime/signals
  Gopkg.lock
  pkg/apis/istio/v1alpha1/register.go
  pkg/cmd/serve/serve.go
Labels: component/cli, component/operator, kind/bug

#414 feat(test): add gRPC support to Test-Service and Test-Generator
  Gopkg.lock
  Makefile
  e2e/http_funcs.go
  e2e/infra/deployment.go
  e2e/infra/test_service.go
  e2e/smoke_test.go
  pkg/cmd/root.go
  pkg/controller/session/session_controller_int_test.go
  test/cmd/test-scenario/generator/generators.go
  test/cmd/test-scenario/generator/modifiers.go
  test/cmd/test-scenario/generator/scenarios.go
  test/cmd/test-scenario/main.go
  test/cmd/test-service/grpc.go
  test/cmd/test-service/handler.go
  test/cmd/test-service/http.go
  test/cmd/test-service/main.go
  test/cmd/test-service/main.pb.go
  test/cmd/test-service/main.proto
  test/cmd/test-service/propagation.go
  test/cmd/test-service/request.go
Labels: internal/test-infra, kind/enhancement

#422 chore(deps): bumps golang to latest release 1.14.2
  .circleci/config.yml
  test/cmd/test-service/main.pb.go
Labels: dependencies, go
