Repository maistra/istio-workspace, pull requests merged in 2020-06, with the labels that each got.

#462 fix: unifies logging usage through wrapper
  .circleci/config.yml
  .golangci.yml
  Gopkg.lock
  Makefile
  cmd/ike/main.go
  pkg/cmd/config/env_vars.go
  pkg/cmd/create/create.go
  pkg/cmd/delete/delete.go
  pkg/cmd/develop/develop.go
  pkg/cmd/install/install.go
  pkg/cmd/root.go
  pkg/cmd/serve/serve.go
  pkg/cmd/version/releases.go
  pkg/cmd/version/version.go
  pkg/cmd/watch/watch.go
  pkg/controller/session/session_controller.go
  pkg/controller/session/session_controller_int_test.go
  pkg/internal/session/session.go
  pkg/internal/session/session_client.go
  pkg/k8s/deployment_test.go
  pkg/k8s/service_test.go
  pkg/log/filtering.go
  pkg/log/log.go
  pkg/openshift/deploymentconfig_test.go
  pkg/shell/funcs.go
  pkg/watch/watch.go
  pkg/watch/watch_builder.go
  test/cmd/test-service/http.go
  test/cmd/test-service/main.go
  test/cmd/test-service/main.pb.go
Labels: component/cli, kind/enhancement

#463 fix: downloads protoc if not available
  Makefile
  scripts/dev/get-protobuf.sh
  test/cmd/test-service/main.pb.go
Labels: internal/infra, kind/bug

#464 chore: removes deploy-operator.sh script
  scripts/dev/deploy-operator.sh
Labels: internal/infra, skip-changelog

#473 fix(doc): uses thumbnail link instead of video tag
  README.adoc
Labels: component/docs, kind/bug, skip-changelog

#472 fix(dev): get_protobuf should use "pwd"
  scripts/dev/get-protobuf.sh
Labels: internal/test-infra, kind/bug

#470 chore: updates transitive deps
  Gopkg.lock
Labels: dependencies, skip-changelog

#469 feat: expose session host route
  e2e/infra/test_service.go
  e2e/smoke_test.go
  pkg/controller/session/session_controller.go
  pkg/controller/session/session_controller_int_test.go
  pkg/istio/destinationrule.go
  pkg/istio/destinationrule_test.go
  pkg/istio/gateway.go
  pkg/istio/gateway_test.go
  pkg/istio/virtualservice.go
  pkg/istio/virtualservice_test.go
  pkg/istio/virtualservicegateway.go
  pkg/istio/virtualservicegatway_test.go
  pkg/k8s/deployment.go
  pkg/k8s/deployment_test.go
  pkg/k8s/service.go
  pkg/k8s/service_test.go
  pkg/model/model.go
  pkg/openshift/deploymentconfig.go
  pkg/openshift/deploymentconfig_test.go
  test/cmd/test-scenario/generator/modifiers.go
  test/cmd/test-scenario/generator/scenarios.go
  test/testclient/getters.go
Labels: component/operator, kind/enhancement

#483 feat(operator): expose host route in session status
  pkg/apis/istio/v1alpha1/session_types.go
  pkg/apis/istio/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/session/model_convert.go
  pkg/controller/session/model_convert_test.go
  pkg/istio/gateway.go
  pkg/istio/gateway_test.go
  pkg/model/model.go
Labels: component/operator, kind/enhancement
