Repository maistra/istio-workspace, pull requests merged in 2020-03, with the labels that each got.

#376 fix(test): generate a suitable deployment resource for a pure k8s ins…
  test/cmd/test-scenario/generators.go
Labels: internal/infra, kind/bug

#374 feat(github): introduces label sync action
  .github/labels.yml
  .github/workflows/update_labels.yml
Labels: internal/infra, kind/enhancement

#381 fix(gh): improves labels descriptions [skip-e2e]
  .github/labels.yml
Labels: internal/test-infra, kind/enhancement, skip-changelog

#380 fix(e2e): add to the members array instead of replacing it
  e2e/infra/test_service.go
Labels: internal/test-infra, kind/bug

#378 feature(operator): find target hostnames via Services instead of nami…
  pkg/apis/istio/v1alpha1/session_types.go
  pkg/apis/istio/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/session/model_convert.go
  pkg/controller/session/model_convert_test.go
  pkg/controller/session/session_controller.go
  pkg/controller/session/session_controller_int_test.go
  pkg/controller/session/session_controller_test.go
  pkg/istio/destinationrule.go
  pkg/istio/virtualservice.go
  pkg/istio/virtualservice_test.go
  pkg/k8s/deployment.go
  pkg/k8s/deployment_test.go
  pkg/k8s/service.go
  pkg/k8s/service_test.go
  pkg/model/model.go
  pkg/openshift/deploymentconfig.go
  pkg/openshift/deploymentconfig_test.go
Labels: component/operator, kind/enhancement

#385 fix: cleans up linter usage
  .golangci.yml
  e2e/http_funcs.go
  e2e/infra/cluster_operations.go
  e2e/infra/istio_operators_setup.go
  e2e/smoke_test.go
  pkg/cmd/completion/completion.go
  pkg/cmd/config/cmd_test.go
  pkg/cmd/create/create.go
  pkg/cmd/delete/delete.go
  pkg/cmd/develop/develop.go
  pkg/cmd/install/install.go
  pkg/cmd/root.go
  pkg/cmd/serve/serve.go
  pkg/cmd/version/version.go
  pkg/controller/session/model_convert.go
  pkg/controller/session/session_controller.go
  pkg/controller/session/session_controller_test.go
  pkg/internal/session/session.go
  pkg/internal/session/session_client.go
  pkg/istio/destinationrule.go
  pkg/istio/destinationrule_test.go
  pkg/istio/virtualservice.go
  pkg/istio/virtualservice_test.go
  pkg/k8s/deployment.go
  pkg/k8s/service.go
  pkg/openshift/deploymentconfig.go
  test/cmd/test-service/main.go
  test/ginkgo_custom_reporter.go
  test/shell/test_setup.go
  test/tmp_file.go
Labels: internal/infra, kind/bug

#375 feature(test): add full dns support to host names in test-generator
  pkg/controller/session/model_convert.go
  pkg/controller/session/model_convert_test.go
  pkg/controller/session/session_controller.go
  pkg/controller/session/session_controller_int_test.go
  pkg/istio/destinationrule.go
  pkg/istio/virtualservice.go
  pkg/istio/virtualservice_test.go
  pkg/k8s/service_test.go
  pkg/model/model.go
  pkg/model/model_suite_test.go
  pkg/model/model_test.go
  test/cmd/test-scenario/generators.go
  test/cmd/test-scenario/generators_test.go
  test/cmd/test-scenario/main.go
  test/cmd/test-scenario/modifiers.go
  test/cmd/test-scenario/scenarios.go
Labels: internal/test-infra, kind/enhancement

#387 fix(operator): give istio-workspace SA auth to create metrics service
  deploy/istio-workspace/role.yaml
  deploy/istio-workspace/role_local.yaml
  pkg/assets/isto-workspace-deploy.go
Labels: component/operator, kind/bug

#386 test(generator): use generator in int test scenario
  pkg/controller/session/session_controller_int_test.go
  test/cmd/test-scenario/generator/generator_suite_test.go
  test/cmd/test-scenario/generator/generators.go
  test/cmd/test-scenario/generator/generators_test.go
  test/cmd/test-scenario/generator/modifiers.go
  test/cmd/test-scenario/generator/scenarios.go
  test/cmd/test-scenario/main.go
Labels: internal/test-infra, kind/enhancement

#388 fix(docs): proper install snippet [skip-e2e]
  README.adoc
  docs/modules/ROOT/pages/getting_started.adoc
Labels: component/docs, kind/bug

#393 fix(operator): remove args and command from telepresence clone
  pkg/template/template.go
  pkg/template/template_test.go
Labels: component/operator, kind/bug

#392 fix(tests): controls tp version env var
  pkg/telepresence/wrapper_test.go
Labels: internal/test-infra, kind/bug

#391 feat(cmd): version cmd prints short semver info [skip-e2e]
  Gopkg.lock
  pkg/cmd/version/version.go
Labels: component/cli, kind/enhancement

#397 release(v0.0.3): highlights of this release [skip-e2e]
  docs/modules/ROOT/pages/dev_guide.adoc
  docs/modules/ROOT/pages/release_notes.adoc
  docs/modules/ROOT/pages/release_notes/release_notes_template.adoc
  docs/modules/ROOT/pages/release_notes/v0.0.3.adoc
Labels: skip-changelog

#396 fix(release): improvements in release shell script [skip-e2e]
  scripts/release.sh
Labels: internal/infra, kind/enhancement

#399 feat(circle): skips e2e tests when /directive in msg
  .circleci/config.yml
Labels: internal/test-infra, kind/enhancement, skip-changelog

#400 docs: improvements identified during the release
  docs/modules/ROOT/pages/cli_reference.adoc
  docs/modules/ROOT/pages/dev_guide.adoc
  docs/modules/ROOT/pages/getting_started.adoc
  docs/modules/ROOT/pages/release_notes/release_notes_template.adoc
  docs/modules/ROOT/pages/release_notes/v0.0.3.adoc
  scripts/release.sh
Labels: component/docs, kind/enhancement
