Repository maistra/istio-workspace, pull requests merged in 2020-05, with the labels that each got.

#429 fix(e2e): use ingress route host as target for http calls
  deploy/istio/base-installation.yaml
  e2e/infra/istio_operators_setup.go
Labels: internal/test-infra, kind/bug

#430 chore(e2e): removes openshift 3.11 tests infra
  .circleci/config.yml
  Makefile
  deploy/istio/base-installation.yaml
  e2e/e2e_suite_test.go
  e2e/infra/cluster_operations.go
  e2e/infra/image_registry.go
  e2e/infra/istio_operators_setup.go
  e2e/infra/test_service.go
  scripts/openshift/deploy-istio.sh
  scripts/openshift/start-cluster.sh
Labels: internal/test-infra, kind/enhancement

#442 feat(ci): caches build results to avoid redundant runs
  .circleci/config.yml
  .gitignore
Labels: internal/infra, kind/enhancement, skip-changelog

#446 build(deps): bump libraries - k8s to 1.16 and istio to 1.4
  Gopkg.lock
  Gopkg.toml
  Makefile
  pkg/apis/addtoscheme_istio_networking_v1alpha3.go
  pkg/apis/istio/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/istio/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/istio/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/istio/v1alpha1/fake/fake_istio_client.go
  pkg/client/clientset/versioned/typed/istio/v1alpha1/fake/fake_session.go
  pkg/client/clientset/versioned/typed/istio/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/istio/v1alpha1/istio_client.go
  pkg/client/clientset/versioned/typed/istio/v1alpha1/session.go
  pkg/controller/session/session_controller_int_test.go
  pkg/istio/destinationrule.go
  pkg/istio/destinationrule_test.go
  pkg/istio/virtualservice.go
  pkg/istio/virtualservice_test.go
  pkg/log/log.go
  pkg/openshift/deploymentconfig.go
  scripts/boilerplate.txt
  test/cmd/test-scenario/generator/generators.go
  test/cmd/test-scenario/generator/modifiers.go
Labels: dependencies

#448 chore(deps): bumps golang to latest release 1.14.3
  .circleci/config.yml
Labels: dependencies, go

#449 feat(cli): if no ports are defined, rely on auto expose from tp
  pkg/cmd/develop/develop.go
  pkg/cmd/develop/develop_test.go
Labels: component/cli, kind/enhancement

#453 feat(tests): builds and pushes test images before the test suite starts
  e2e/e2e_suite_test.go
  e2e/error_path_test.go
  e2e/infra/cluster_setup.go
  e2e/infra/image_registry.go
  e2e/infra/istio_operators_setup.go
  e2e/infra/test_service.go
  e2e/operator_installation_test.go
  e2e/smoke_test.go
Labels: internal/test-infra, kind/enhancement

#452 feat(cli): support multiple port expose bindings
  pkg/cmd/develop/develop.go
  pkg/cmd/develop/develop_test.go
Labels: component/cli, kind/enhancement

#454 fix(doc): explain passing multi value flags as repeated flags
  pkg/cmd/develop/develop.go
  pkg/cmd/format/help_format.go
Labels: component/cli, component/docs, kind/enhancement
