Repository maistra/istio-workspace, pull requests merged in 2020-01, with the labels that each got.

#340 fix(deps): locks openshift api on commit hash
  Gopkg.toml
Labels: dependencies, skip-changelog

#343 fix: updates issue tpl after introducing kind prefix [skip-e2e]
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: skip-changelog

#342 fix(template): creates replica if not exists
  Gopkg.lock
  pkg/template/template.go
  pkg/template/template_test.go
Labels: component/operator, kind/bug

#344 feat: logs version when starting the operator
  pkg/cmd/root.go
  pkg/cmd/serve/serve.go
  pkg/cmd/version/version.go
Labels: component/operator, kind/enhancement

#348 chore(build): bumps golang to latest 1.13.6
  .circleci/config.yml
Labels: go, internal/infra

#349 fix: cleans up session on error (wrong deployment)
  e2e/error_path_test.go
  e2e/root_cli_test.go
  pkg/internal/session/session.go
  pkg/internal/session/session_client.go
  pkg/internal/session/types.go
Labels: component/operator, kind/bug

#351 fix(operator): revert all manipulated virtual service routes
  pkg/istio/virtualservice.go
  pkg/istio/virtualservice_test.go
Labels: component/operator, kind/bug

#354 feat: introduces ENV_FILE var to overwrite variables used in tests
  Gopkg.lock
  Gopkg.toml
  Makefile
  e2e/e2e_suite_test.go
Labels: internal/test-infra
