Repository maistra/istio-workspace, pull requests merged in 2020-09, with the labels that each got.

#529 feat(operator): add 'existing' strategy
  pkg/k8s/deployment.go
  pkg/k8s/deployment_test.go
  pkg/model/model.go
  pkg/openshift/deploymentconfig.go
  pkg/openshift/deploymentconfig_test.go
Labels: component/operator, kind/enhancement

#531 feat(client): make client wait condition configurable
  .circleci/config.yml
  pkg/internal/session/session.go
Labels: component/cli, kind/enhancement

#532 fix: sets registry to internal before running operator tests
  e2e/infra/image_registry.go
  e2e/infra/istio_operators_setup.go
  e2e/infra/test_service.go
  e2e/operator_installation_test.go
Labels: internal/test-infra, kind/bug
