Repository maistra/istio-workspace, pull requests merged in 2021-05, with the labels that each got.

#828 fix(error): handle no destination rules found error
  pkg/istio/destinationrule.go
  pkg/istio/destinationrule_test.go
  pkg/istio/gateway.go
  pkg/istio/virtualservice.go
  pkg/k8s/deployment.go
  pkg/k8s/service.go
  pkg/model/model.go
  pkg/openshift/deploymentconfig.go
Labels: component/operator, kind/bug

#835 fix(session): makes sure session name follows RFC 1123
  pkg/internal/session/session.go
  pkg/internal/session/session_test.go
  pkg/istio/destinationrule.go
  pkg/naming/name_generator.go
Labels: component/cli, kind/bug

#831 fix: wrapped ike command uses full path of the parent cmd
  cmd/manager/main.go
  pkg/cmd/develop/cmd.go
  pkg/cmd/develop/cmd_test.go
Labels: component/cli, kind/bug

#836 chore(gh-actions): pins ubuntu to ubuntu-20.04
  .github/workflows/cleanup_pr_images.yml
  .github/workflows/golangci_lint.yml
  .github/workflows/release_pr.yml
  .github/workflows/release_tag.yml
  .github/workflows/update_labels.yml
  .github/workflows/validate_circleci.yml
Labels: internal/infra, kind/enhancement

#837 feat(log): introduce emperror for errors with details
  api/apis.go
  controllers/session/session_controller.go
  e2e/http_funcs.go
  go.mod
  go.sum
  pkg/assets/loader.go
  pkg/cmd/completion/cmd.go
  pkg/cmd/config/config.go
  pkg/cmd/create/cmd.go
  pkg/cmd/delete/cmd.go
  pkg/cmd/develop/cmd.go
  pkg/cmd/develop/hint.go
  pkg/cmd/execute/cmd.go
  pkg/cmd/internal/session/session_func.go
  pkg/cmd/root.go
  pkg/cmd/serve/cmd.go
  pkg/cmd/version/cmd.go
  pkg/cmd/version/releases.go
  pkg/internal/session/session.go
  pkg/internal/session/session_client.go
  pkg/internal/session/session_client_test.go
  pkg/internal/session/session_test.go
  pkg/istio/destinationrule.go
  pkg/istio/destinationrule_test.go
  pkg/istio/gateway.go
  pkg/istio/virtualservice.go
  pkg/k8s/deployment.go
  pkg/k8s/service.go
  pkg/log/emperror.go
  pkg/log/emperror_test.go
  pkg/log/filtering.go
  pkg/log/log.go
  pkg/openshift/deploymentconfig.go
  pkg/template/template.go
  pkg/watch/watch.go
  pkg/watch/watch_builder.go
  pkg/watch/watch_test.go
  test/cmd/test-service/main.go
  test/testclient/getters.go
Labels: component/ci, kind/enhancement

#838 fix(operator): mutate both connected and not vs
  build/ContainerfileTestPrepared
  e2e/smoke_test.go
  pkg/istio/destinationrule.go
  pkg/istio/virtualservice.go
  test/cmd/test-scenario/generator/generators.go
Labels: component/operator, kind/bug

#842 chore(golint): bumps to 1.40 and enables wrapcheck
  .github/workflows/golangci_lint.yml
  .golangci.yml
  Makefile
  api/maistra/v1alpha1/session_types.go
  config/crd/bases/maistra.io_sessions.yaml
  pkg/cmd/develop/cmd.go
  pkg/cmd/execute/cmd.go
  pkg/cmd/format/help_format.go
  pkg/log/log.go
  pkg/model/model.go
  pkg/openshift/deploymentconfig.go
  pkg/telepresence/wrapper.go
Labels: dependencies, internal/test-infra

#843 fix(shellcheck): reworks ike-create task
  integration/tekton/tasks/ike-create/ike-create.yaml
  integration/tekton/tasks/ike-delete/ike-delete.yaml
  integration/tekton/tasks/ike-session-url/ike-session-url.yaml
Labels: component/ci, kind/bug

#848 fix(make): sets mv with --force flag to avoid prompting
  Makefile
Labels: internal/infra, kind/bug
