Repository maistra/istio-workspace, pull requests merged in 2021-07, with the labels that each got.

#853 feat(circleci): aggregates junit reports for CircleCI
  .circleci/config.yml
  .gitignore
  Makefile
Labels: internal/infra, kind/enhancement

#854 chore(lint): bumps golangci-lint to latest release
  .github/workflows/golangci_lint.yml
  Makefile
  controllers/session/session_controller_int_test.go
Labels: internal/infra, skip-changelog

#855 feat(operator): bumps operator-sdk to latest v1.8.1
  .circleci/config.yml
  Makefile
Labels: dependencies

#858 feat(operator): reworks Controller internals to be stateless
  .circleci/config.yml
  .gitignore
  Makefile
  api/maistra/v1alpha1/register.go
  api/maistra/v1alpha1/session_types.go
  api/maistra/v1alpha1/zz_generated.deepcopy.go
  build/bundle.Containerfile
  config/crd/bases/maistra.io_sessions.yaml
  controllers/session/model_convert.go
  controllers/session/model_convert_test.go
  controllers/session/session_controller.go
  controllers/session/session_controller_int_test.go
  controllers/session/session_controller_test.go
  e2e/smoke_test.go
  go.mod
  go.sum
  integration/tekton/tasks/ike-create/ike-create.yaml
  integration/tekton/tasks/ike-session-url/ike-session-url.yaml
  pkg/cmd/create/cmd.go
  pkg/cmd/develop/cmd.go
  pkg/cmd/develop/hint.go
  pkg/cmd/develop/hint_test.go
  pkg/cmd/internal/session/session_func.go
  pkg/internal/session/session.go
  pkg/internal/session/session_test.go
  pkg/istio/destinationrule.go
  pkg/istio/destinationrule_test.go
  pkg/istio/gateway.go
  pkg/istio/gateway_test.go
  pkg/istio/virtualservice.go
  pkg/istio/virtualservice_test.go
  pkg/istio/virtualservicegateway.go
  pkg/istio/virtualservicegateway_test.go
  pkg/k8s/deployment.go
  pkg/k8s/deployment_test.go
  pkg/k8s/service.go
  pkg/k8s/service_test.go
  pkg/model/locator.go
  pkg/model/model.go
  pkg/model/model_test.go
  pkg/model/modificator.go
  pkg/model/sync.go
  pkg/model/types.go
  pkg/model/validator.go
  pkg/model/versioning.go
  pkg/naming/name_generator.go
  pkg/openshift/deploymentconfig.go
  pkg/openshift/deploymentconfig_test.go
  pkg/reference/marker.go
  pkg/shell/funcs.go
Labels: component/operator, kind/enhancement

#865 feat: adds condition when the source ref is located
  controllers/session/conditions.go
  controllers/session/session_controller.go
  e2e/error_path_test.go
  e2e/install_mode_test.go
  e2e/smoke_test.go
  pkg/internal/session/session.go
  pkg/reference/enqueue_annotations.go
  pkg/shell/funcs.go
  test/cmd/test-service/main.go
Labels: component/operator, kind/enhancement

#867 Populate the missing Status fields RefNames & Strategies
  build/bundle.Containerfile
  config/manifests/bases/istio-workspace-operator.clusterserviceversion.yaml
  controllers/session/session_controller.go
Labels: component/operator, kind/bug

#866 feat(operator): add validation chain that blocks on error
  api/maistra/v1alpha1/session_types.go
  controllers/session/conditions.go
  controllers/session/session_controller.go
  controllers/session/session_controller_int_test.go
  controllers/session/validation.go
  pkg/cmd/develop/cmd.go
  pkg/internal/session/session.go
  pkg/internal/session/session_test.go
  pkg/model/validator.go
Labels: component/operator, kind/enhancement
