Repository maistra/istio-workspace, pull requests merged in 2021-03, with the labels that each got.

#719 feat(operator): watch manipulated resources for reconcile on change
  config/crd/bases/maistra.io_sessions.yaml
  controllers/session/session_controller.go
  controllers/session/session_controller_int_test.go
  controllers/session/session_controller_test.go
  e2e/smoke_test.go
  pkg/istio/destinationrule.go
  pkg/istio/destinationrule_test.go
  pkg/istio/gateway.go
  pkg/istio/gateway_test.go
  pkg/istio/virtualservice.go
  pkg/istio/virtualservice_test.go
  pkg/k8s/deployment.go
  pkg/k8s/deployment_test.go
  pkg/model/model.go
  pkg/openshift/deploymentconfig.go
  pkg/openshift/deploymentconfig_test.go
  pkg/reference/enqueue_annotations.go
  pkg/reference/enqueue_annotations_test.go
  pkg/reference/reference_suite_test.go
Labels: component/operator, doc/highlight, kind/enhancement

#730 fix: improves readability of section headers in release notes
  docs/modules/ROOT/pages/release_notes/release_notes_template.adoc
  docs/modules/ROOT/pages/release_notes/v0.0.5.adoc
  docs/modules/ROOT/pages/release_notes/v0.0.6.adoc
  docs/modules/ROOT/pages/release_notes/v0.0.7.adoc
  docs/modules/ROOT/pages/release_notes/v0.0.8.adoc
Labels: skip-changelog

#728 feat: initial move of Tekton tasks
  Makefile
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/cli_reference.adoc
  docs/modules/ROOT/pages/getting_started.adoc
  docs/modules/ROOT/pages/integration/tekton/overview.adoc
  docs/modules/ROOT/pages/integration/tekton/tasks/ike-create.adoc
  docs/modules/ROOT/pages/integration/tekton/tasks/ike-delete.adoc
  docs/modules/ROOT/pages/integration/tekton/tasks/ike-session-url.adoc
  docs/modules/ROOT/pages/release_notes.adoc
  go.mod
  go.sum
  integration/tekton/README.md
  integration/tekton/tasks/ike-create/ike-create.yaml
  integration/tekton/tasks/ike-create/samples/ike-create.yaml
  integration/tekton/tasks/ike-create/tests/pre-apply-task-hook.sh
  integration/tekton/tasks/ike-create/tests/run.yaml
  integration/tekton/tasks/ike-delete/ike-delete.yaml
  integration/tekton/tasks/ike-delete/samples/ike-delete.yaml
  integration/tekton/tasks/ike-delete/tests/pre-apply-task-hook.sh
  integration/tekton/tasks/ike-delete/tests/run.yaml
  integration/tekton/tasks/ike-session-url/ike-session-url.yaml
  integration/tekton/tasks/ike-session-url/samples/ike-session-url.yaml
  integration/tekton/tasks/ike-session-url/tests/pre-apply-task-hook.sh
  integration/tekton/tasks/ike-session-url/tests/run.yaml
  tools.go
Labels: component/ci, kind/enhancement

#734 fix(circle): updates executor machine to Ubuntu 20.04
  .circleci/config.yml
Labels: internal/infra, kind/enhancement

#741 fix: do not ignore errors when outputting in json
  pkg/cmd/root.go
  pkg/log/log.go
Labels: component/cli, component/operator, kind/bug

#738 feat(tekton): adds e2e tests for Tekton tasks
  .circleci/config.yml
  .github/workflows/golangci_lint.yml
  .golangci.yml
  Makefile
  docs/modules/ROOT/pages/integration/tekton/overview.adoc
  docs/modules/ROOT/pages/integration/tekton/tasks/ike-create.adoc
  docs/modules/ROOT/pages/integration/tekton/tasks/ike-delete.adoc
  docs/modules/ROOT/pages/integration/tekton/tasks/ike-session-url.adoc
  e2e/infra/tekton.go
  e2e/install_mode_test.go
  e2e/smoke_test.go
  integration/tekton/tasks/ike-create/ike-create.yaml
  integration/tekton/tasks/ike-create/samples/ike-create.yaml
  integration/tekton/tasks/ike-create/tests/pre-apply-task-hook.sh
  integration/tekton/tasks/ike-create/tests/run.yaml
  integration/tekton/tasks/ike-delete/ike-delete.yaml
  integration/tekton/tasks/ike-delete/samples/ike-delete.yaml
  integration/tekton/tasks/ike-delete/tests/pre-apply-task-hook.sh
  integration/tekton/tasks/ike-delete/tests/run.yaml
  integration/tekton/tasks/ike-session-url/ike-session-url.yaml
  integration/tekton/tasks/ike-session-url/samples/ike-session-url.yaml
  integration/tekton/tasks/ike-session-url/tests/pre-apply-task-hook.sh
  integration/tekton/tasks/ike-session-url/tests/run.yaml
  pkg/cmd/create/cmd_test.go
  pkg/internal/session/session.go
  scripts/release/tektoncatalog.sh
  test/os_env.go
  test/shell/funcs.go
Labels: internal/test-infra, kind/enhancement

#742 chore: rewords project description
  README.md
  docs/modules/ROOT/pages/cli_reference.adoc
  docs/modules/ROOT/pages/comparisons/service_preview.adoc
  docs/modules/ROOT/pages/contribution_guide.adoc
  docs/modules/ROOT/pages/getting_started.adoc
  docs/modules/ROOT/pages/ideas.adoc
  docs/modules/ROOT/pages/index.adoc
  scripts/release/operatorhub-pr-template.md
Labels: component/docs, kind/enhancement

#743 fix(operator): avoid reusing version in clone name
  pkg/istio/destinationrule_test.go
  pkg/istio/virtualservice_test.go
  pkg/k8s/deployment_test.go
  pkg/model/model.go
  pkg/openshift/deploymentconfig_test.go
Labels: component/operator, kind/bug

#744 chore(circle): improves build speed
  .circleci/config.yml
  Makefile
  go.sum
Labels: internal/test-infra, kind/enhancement, skip-changelog

#746 fix(script): do not require GITHUB_TOKEN in dryRun mode
  scripts/release/operatorhub.sh
  scripts/release/tektoncatalog.sh
Labels: internal/infra, kind/bug, skip-changelog

#760 fix(operator): set klog to unify loggers
  go.mod
  pkg/log/log.go
Labels: component/operator, kind/bug

#762 fix(bundle): make CSV sample more realistic
  config/samples/maistra.io_v1alpha1_session.yaml
Labels: component/operator, kind/enhancement

#763 feat(circleci): caches snap deps
  .circleci/config.yml
Labels: internal/infra, kind/enhancement

#769 revert: build(deps): Bump github.com/spf13/afero from 1.5.1 to 1.6.0
  go.mod
  go.sum
Labels: reason/breaking-changes, skip-changelog

#764 feat(circleci): updates microk8s to 1.19 stream
  .circleci/config.yml
Labels: internal/test-infra, kind/enhancement

#767 feat(operator): add LastTransitionTime to status
  api/maistra/v1alpha1/session_types.go
  api/maistra/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/maistra.io_sessions.yaml
  controllers/session/model_convert.go
  controllers/session/model_convert_test.go
  pkg/model/model.go
Labels: component/operator, kind/enhancement

#768 feat(circleci): introduces env var to force cache invalidation
  .circleci/config.yml
Labels: internal/infra, kind/enhancement

#773 feat(operator): adds conditions with type, status, reason and msg
  api/maistra/v1alpha1/session_types.go
  api/maistra/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/maistra.io_sessions.yaml
  controllers/session/model_convert.go
Labels: component/operator, kind/enhancement

#778 fix(tekton): ability to define base branch through env var when opening PR
  scripts/release/operatorhub.sh
  scripts/release/tektoncatalog.sh
Labels: internal/infra, kind/bug

#779 feat(circleci): ability to skip the build by using /skip-build directive
  .circleci/config.yml
Labels: internal/infra, kind/enhancement, skip-changelog

#780 fix(gh-actions): lint-prepare should not compile the code
  Makefile
Labels: internal/infra, kind/bug, skip-changelog

#784 fix(infra): run go mod tidy to match dependabot go.sum
  Makefile
Labels: internal/infra, kind/bug

#785 feat(operator): split action and success state in model
  controllers/session/model_convert.go
  controllers/session/model_convert_test.go
  pkg/istio/destinationrule.go
  pkg/istio/gateway.go
  pkg/istio/virtualservice.go
  pkg/k8s/deployment.go
  pkg/model/model.go
  pkg/openshift/deploymentconfig.go
Labels: component/operator, kind/enhancement

#786 feat(operator): enhances CLI output for CRD with custom columns
  api/maistra/v1alpha1/session_types.go
  api/maistra/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/maistra.io_sessions.yaml
  controllers/session/session_controller.go
  pkg/cmd/develop/hint.go
Labels: component/cli, kind/enhancement
