Repository maistra/istio-workspace, pull requests merged in 2021-09, with the labels that each got.

#883 chore(circleci): bumps microk8s to 1.22
  .circleci/config.yml
  integration/tekton/tasks/ike-create/ike-create.yaml
  integration/tekton/tasks/ike-delete/ike-delete.yaml
  integration/tekton/tasks/ike-session-url/ike-session-url.yaml
Labels: internal/test-infra

#884 chore(circleci): bumps golang builds to 1.17
  .circleci/config.yml
Labels: internal/infra, dependencies

#875 feat(operator): add podStatus ui wheel to component
  api/maistra/v1alpha1/api_suite_test.go
  api/maistra/v1alpha1/session_types.go
  api/maistra/v1alpha1/session_types_test.go
  api/maistra/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/maistra.io_sessions.yaml
  config/manifests/bases/istio-workspace-operator.clusterserviceversion.yaml
  controllers/session/session_controller.go
  controllers/session/session_controller_int_test.go
  pkg/k8s/service.go
Labels: kind/enhancement, component/operator

#910 fix(operatorhub): uses ansible test scripts from new repo
  .github/workflows/operator_bundle_tests.yml
  Makefile
  scripts/release/operatorhub.sh
Labels: internal/test-infra, component/operator

#900 feat(gh-actions): defines catlin tekton task linter job
  .github/workflows/golangci_lint.yml
  .github/workflows/tekton.yml
  integration/tekton/tasks/ike-create/ike-create.yaml
  integration/tekton/tasks/ike-session-url/ike-session-url.yaml
Labels: kind/enhancement, internal/test-infra

#909 feat: adds workspace. prefix to apiGroup
  api/maistra/v1alpha1/doc.go
  api/maistra/v1alpha1/register.go
  api/maistra/v1alpha1/zz_generated.deepcopy.go
  api/maistra/v1alpha1/zz_generated.defaults.go
  config/crd/bases/workspace.maistra.io_sessions.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  config/rbac/session_editor_role.yaml
  config/samples/kustomization.yaml
  config/samples/workspace.maistra.io_v1alpha1_session.yaml
  controllers/session/session_controller.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/maistra/v1alpha1/fake/fake_maistra_client.go
  pkg/client/clientset/versioned/typed/maistra/v1alpha1/fake/fake_session.go
  pkg/client/clientset/versioned/typed/maistra/v1alpha1/maistra_client.go
  pkg/client/clientset/versioned/typed/maistra/v1alpha1/session.go
  pkg/internal/session/session.go
  pkg/internal/session/session_client.go
  pkg/internal/session/session_client_test.go
  pkg/internal/session/session_test.go
Labels: kind/enhancement, component/operator

#915 fix(scripts): sets failure options to fail fast
  scripts/dev/get-protobuf.sh
  scripts/get.sh
  scripts/release/operatorhub.sh
  scripts/release/release.sh
  scripts/release/tektoncatalog.sh
  scripts/release/validate.sh
  scripts/release/validate_semver.sh
Labels: kind/enhancement, internal/infra, skip-changelog

#908 build(golang): bumps golang builds to 1.17.1
  .circleci/config.yml
  .github/workflows/golangci_lint.yml
  go.mod
Labels: internal/infra, dependencies

#916 build(deps): Bump k8s.io/api from 0.22.1 to 0.22.2
  go.mod
  go.sum
Labels: dependencies, go

#923 chore(test): makes tmp file system instance-based
  controllers/session/session_controller_int_test.go
  e2e/bash_completion_test.go
  e2e/error_path_test.go
  e2e/smoke_test.go
  pkg/assets/loader_test.go
  pkg/cmd/config/cmd_test.go
  pkg/cmd/config/config_suite_test.go
  pkg/cmd/create/create_suite_test.go
  pkg/cmd/delete/delete_suite_test.go
  pkg/cmd/develop/cmd_test.go
  pkg/cmd/develop/develop_suite_test.go
  pkg/cmd/execute/cmd_test.go
  pkg/cmd/execute/execute_suite_test.go
  pkg/cmd/internal/session/session_suite_test.go
  pkg/watch/watch_suite_test.go
  pkg/watch/watch_test.go
  test/tmp_file.go
Labels: kind/enhancement, internal/test-infra

#924 feat(circleci): skips build and e2e tests for non-code changes
  .circleci/config.yml
Labels: kind/enhancement, internal/test-infra, skip-changelog

#922 feat(make): renames docker to container/image
  .circleci/config.yml
  Makefile
  docs/modules/ROOT/pages/dev_guide.adoc
  e2e/e2e_suite_test.go
  e2e/infra/image_registry.go
  e2e/infra/istio_operators_setup.go
  e2e/infra/test_service.go
  e2e/smoke_test.go
  pkg/cmd/config/env_vars.go
Labels: kind/enhancement, internal/infra

#931 build(deps): Bumps protoc from 3.15.8 to 3.18.0
  scripts/dev/get-protobuf.sh
  test/cmd/test-service/main.pb.go
Labels: dependencies, go

#920 fix(operator): add new groupname to csv config
  config/manifests/bases/istio-workspace-operator.clusterserviceversion.yaml
Labels: kind/bug, component/operator

#933 fix(operator): runs the same test suite as on hub PR
  .circleci/config.yml
  .github/workflows/operator_bundle_tests.yml
  api/maistra/v1alpha1/session_types.go
  config/crd/bases/workspace.maistra.io_sessions.yaml
  scripts/release/operatorhub/publish.sh
  scripts/release/operatorhub/test.sh
Labels: kind/bug, internal/test-infra
