Repository maistra/istio-workspace, pull requests merged in 2021-02, with the labels that each got.

#640 fix(e2e): replace usage of ruby with python to limit dev container size
  e2e/error_path_test.go
  e2e/infra/test_service.go
  e2e/smoke_test.go
Labels: MVP, internal/test-infra, kind/enhancement

#650 fix(cli): watch run command status and log errors
  pkg/cmd/execute/cmd.go
Labels: component/cli, kind/bug

#651 fix(log): add log caller to structured logger
  pkg/log/log.go
Labels: component/cli, component/operator, kind/enhancement

#652 chore: moves dev images to rely on maistra-dev repo
  .circleci/config.yml
  .github/workflows/cleanup_pr_images.yml
  Makefile
  e2e/infra/image_registry.go
  e2e/infra/test_service.go
  e2e/smoke_test.go
  pkg/cmd/config/env_vars.go
  test/cmd/test-scenario/main.go
Labels: internal/infra, internal/test-infra, kind/enhancement

#655 fix: refers to PR head ref branch name for image build
  .circleci/config.yml
  .github/workflows/cleanup_pr_images.yml
Labels: internal/test-infra, kind/bug, skip-changelog

#657 fix(circle): tree hash propagates properly to avoid redundant job runs
  .circleci/config.yml
  .gitignore
Labels: internal/test-infra, kind/bug

#660 fix(release): add status on success
  .github/workflows/release_pr.yml
Labels: internal/infra, kind/bug

#662 fix(release): add status to our new commit
  .github/workflows/release_pr.yml
Labels: internal/infra, kind/bug

#663 fix(release): output the string v of the buffer
  .github/workflows/release_pr.yml
Labels: internal/infra, kind/bug

#664 fix(release): remove newline from rev-parse
  .github/workflows/release_pr.yml
Labels: internal/infra, kind/bug

#665 fix(release): write success status to new commit
  .github/workflows/release_pr.yml
Labels: internal/infra, kind/bug, skip-changelog

#666 fix(release): add validation step to /release
  .github/workflows/release_pr.yml
Labels: internal/infra, kind/bug, skip-changelog

#672 chore(make): moves asset generation away from setup section
  Makefile
Labels: internal/infra, skip-changelog

#667 release: add bundle push step to release process
  .circleci/config.yml
  .github/actions/release.sh
  Makefile
  go.mod
  tools.go
Labels: internal/infra, kind/bug, skip-changelog

#673 feat(make): adds target to generate release notes template
  .github/actions/validate.sh
  Makefile
Labels: internal/infra, kind/enhancement, skip-changelog

#677 fix(docs): inserts release notes placeholder to aggregated page
  .github/actions/release.sh
  docs/modules/ROOT/pages/release_notes.adoc
Labels: internal/infra, kind/bug, skip-changelog

#676 fix(bundle): sets IKE_VERSION for making bundle
  .github/actions/release.sh
  Makefile
Labels: internal/infra, kind/bug, skip-changelog

#681 build(deps): bump version of istio.io/api and istio.io/client-go
  go.mod
  go.sum
Labels: dependencies, go, needs-ok-to-test

#682 fix(cli): add k8s auth package
  cmd/ike/main.go
Labels: component/cli, kind/enhancement, needs-ok-to-test

#685 feat(operator): automates operator bundle submission
  .circleci/config.yml
  .github/workflows/release_pr.yml
  Makefile
  build/bundle.Dockerfile
  config/manifests/bases/istio-workspace-operator.clusterserviceversion.yaml
  e2e/infra/istio_operators_setup.go
  scripts/release/operatorhub-pr-template.md
  scripts/release/operatorhub.sh
  scripts/release/release.sh
  scripts/release/validate.sh
  scripts/release/validate_semver.sh
Labels: internal/infra, kind/enhancement

#687 fix(circle): uses custom gpg program to sign commits
  .circleci/config.yml
Labels: internal/infra, kind/bug

#689 fix(release): enables operatorhub signed commits
  .circleci/config.yml
  Makefile
  config/manager/kustomization.yaml
  scripts/release/operatorhub-pr-template.md
  scripts/release/operatorhub.sh
Labels: internal/infra, kind/bug

#690 feat(gh-actions): enables /help cmd for releases
  .github/workflows/release_pr.yml
Labels: internal/infra, kind/enhancement

#680 feat(operator): support MultiNamespace install mode
  Makefile
  config/manifests/bases/istio-workspace-operator.clusterserviceversion.yaml
  e2e/install_mode_test.go
  pkg/cmd/serve/cmd.go
Labels: component/operator, kind/enhancement

#692 feat(cli): print usage hint including exposed hosts
  pkg/cmd/develop/cmd.go
  pkg/cmd/develop/hint.go
  pkg/cmd/develop/hint_test.go
Labels: component/cli, kind/enhancement

#693 chore: sets err buffer to be captured for tests
  test/cmd.go
Labels: internal/test-infra, kind/enhancement

#695 fix(release): avoid triggering e2e tests on release changes
  .github/workflows/release_pr.yml
  scripts/release/release.sh
Labels: internal/infra, kind/enhancement, skip-changelog

#698 fix(operator): add required metadata for Operator Hub deployment
  Makefile
  config/manifests/bases/istio-workspace-operator.clusterserviceversion.yaml
Labels: component/operator, internal/infra, skip-changelog

#701 fix(operator): add route to status
  api/maistra/v1alpha1/session_types.go
  api/maistra/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/maistra.io_sessions.yaml
  controllers/session/model_convert.go
  controllers/session/session_controller.go
  controllers/session/session_controller_test.go
  pkg/cmd/develop/cmd.go
  pkg/internal/session/session.go
  pkg/internal/session/session_test.go
Labels: component/operator, kind/enhancement

#703 feat(operator): add description for crd in csv
  PROJECT
  api/maistra/v1alpha1/session_types.go
  config/manifests/bases/istio-workspace-operator.clusterserviceversion.yaml
Labels: component/operator, kind/enhancement

#704 fix(doc): add better description to the crd
  api/maistra/v1alpha1/session_types.go
  config/crd/bases/maistra.io_sessions.yaml
  config/manifests/bases/istio-workspace-operator.clusterserviceversion.yaml
Labels: component/docs, kind/enhancement

#705 fix(doc): regenerate crd to update docs
  config/crd/bases/maistra.io_sessions.yaml
Labels: component/operator, kind/bug, skip-changelog

#715 fix(operator): move to use leader election by lease
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role_binding.yaml
  pkg/cmd/serve/cmd.go
Labels: component/operator, kind/bug, reason/breaking-changes

#716 chore(gh): add doc/highlight label
  .github/labels.yml
Labels: internal/infra, kind/enhancement, skip-changelog

#717 fix(cli): guard against possible nil Route
  pkg/internal/session/session.go
Labels: component/cli, kind/bug
