Repository maistra/istio-workspace, pull requests merged in 2021-04, with the labels that each got.

#792 fix(lint): enables goerr113
  .golangci.yml
  pkg/cmd/config/config.go
  pkg/cmd/develop/cmd.go
  pkg/cmd/serve/cmd.go
  pkg/internal/session/session.go
  pkg/istio/virtualservice.go
  pkg/reference/enqueue_annotations.go
  pkg/telepresence/wrapper.go
  pkg/template/template.go
  test/matchers/string_matchers.go
Labels: internal/infra, kind/bug

#793 feat(operator): supports kind as part of a ref name
  .golangci.yml
  Makefile
  api/maistra/v1alpha1/session_types.go
  config/crd/bases/maistra.io_sessions.yaml
  controllers/session/model_convert.go
  controllers/session/model_convert_test.go
  controllers/session/session_controller.go
  controllers/session/session_controller_int_test.go
  e2e/bash_completion_test.go
  e2e/e2e_suite_test.go
  e2e/infra/cluster_setup.go
  e2e/infra/istio_operators_setup.go
  e2e/infra/test_service.go
  e2e/install_mode_test.go
  e2e/smoke_test.go
  pkg/istio/destinationrule_test.go
  pkg/istio/gateway_test.go
  pkg/istio/virtualservice_test.go
  pkg/istio/virtualservicegateway_test.go
  pkg/k8s/deployment.go
  pkg/k8s/deployment_test.go
  pkg/k8s/service_test.go
  pkg/model/model.go
  pkg/model/model_test.go
  pkg/openshift/deploymentconfig.go
  pkg/openshift/deploymentconfig_test.go
Labels: component/cli, component/operator, doc/highlight, kind/enhancement

#799 feat(operator): creates new destinationrules instead of manipulating
  controllers/session/model_convert_test.go
  controllers/session/session_controller_int_test.go
  e2e/install_mode_test.go
  pkg/istio/destinationrule.go
  pkg/istio/destinationrule_test.go
  pkg/istio/gateway_test.go
  pkg/istio/istio_suite_test.go
  pkg/k8s/k8s_suite_test.go
  pkg/model/model.go
  pkg/reference/enqueue_annotations.go
  pkg/template/template_test.go
  test/testclient/getters.go
Labels: component/operator, kind/enhancement

#805 fix(release): add quotes to tekton version in yaml
  .circleci/config.yml
  Makefile
  integration/tekton/tasks/ike-create/ike-create.yaml
  integration/tekton/tasks/ike-delete/ike-delete.yaml
  integration/tekton/tasks/ike-session-url/ike-session-url.yaml
Labels: internal/infra, kind/bug

#806 fix(release): add skip-build directive to release commits
  .github/workflows/release_pr.yml
  Makefile
  scripts/release/release.sh
Labels: internal/infra, kind/enhancement

#807 fix(build): set go_package in protoc to comply with new v
  Makefile
  scripts/dev/get-protobuf.sh
  test/cmd/test-service/main.pb.go
  test/cmd/test-service/main.proto
Labels: internal/infra, kind/bug

#808 feat(operator): new destinationrule use the same trafficPolicy
  pkg/istio/destinationrule.go
  pkg/istio/destinationrule_test.go
Labels: component/operator, kind/enhancement

#812 feat(gh-actions): infers version from title
  .github/workflows/release_pr.yml
Labels: internal/infra, kind/enhancement

#813 feat(gh-actions): squashes pre-release commits
  scripts/release/release.sh
Labels: internal/infra, kind/enhancement

#815 chore: minor improvements around noglobals linter
  controllers/session/session_controller_test.go
  pkg/cmd/serve/cmd.go
  pkg/shell/funcs.go
  pkg/template/template_test.go
  test/cmd/test-service/main.pb.go
Labels: internal/infra, kind/enhancement, skip-changelog

#814 fix(operator): increase operator resource limits
  config/manager/manager.yaml
  e2e/infra/pod_state.go
  e2e/smoke_test.go
Labels: component/operator, kind/bug

#817 fix(tekton): reworks shell scripts to comply with SC
  e2e/smoke_test.go
  integration/tekton/tasks/ike-create/ike-create.yaml
  integration/tekton/tasks/ike-session-url/ike-session-url.yaml
Labels: component/ci, kind/bug

#809 fix(makefile): executes OC cli only if needed
  Makefile
  e2e/error_path_test.go
  e2e/smoke_test.go
Labels: internal/test-infra, kind/bug

#816 chore(docs): updates release process description
  docs/modules/ROOT/assets/images/diagrams/automation-release.svg
  docs/modules/ROOT/assets/images/diagrams/release-automation.svg
  docs/modules/ROOT/pages/dev_guide.adoc
Labels: component/docs, kind/enhancement

#820 chore(circleci): uses different account for release images
  .circleci/config.yml
Labels: internal/infra, kind/enhancement, skip-changelog

#810 fix(e2e): fails test if background develop cmd fails
  e2e/smoke_test.go
Labels: internal/test-infra, kind/enhancement

#811 build(deps): Bump github.com/operator-framework/operator-sdk from 1.3.0 to 1.6.1
  .circleci/config.yml
  Makefile
  PROJECT
  build/bundle.Dockerfile
  config/prometheus/monitor.yaml
  controllers/session/session_controller_int_test.go
  controllers/session/session_suite_test.go
  e2e/infra/cluster_setup.go
  e2e/infra/istio_operators_setup.go
  e2e/infra/pod_state.go
  e2e/infra/test_service.go
  e2e/smoke_test.go
  go.mod
  go.sum
  pkg/assets/assets_suite_test.go
  pkg/cmd/config/config_suite_test.go
  pkg/cmd/create/create_suite_test.go
  pkg/cmd/delete/delete_suite_test.go
  pkg/cmd/develop/develop_suite_test.go
  pkg/cmd/execute/cmd.go
  pkg/cmd/execute/cmd_test.go
  pkg/cmd/execute/execute_suite_test.go
  pkg/cmd/internal/session/session_suite_test.go
  pkg/cmd/version/version_suite_test.go
  pkg/internal/session/session_suite_test.go
  pkg/istio/istio_suite_test.go
  pkg/k8s/k8s_suite_test.go
  pkg/model/model_suite_test.go
  pkg/naming/k8s_naming_suite_test.go
  pkg/openshift/openshift_suite_test.go
  pkg/reference/reference_suite_test.go
  pkg/telepresence/telepresence_suite_test.go
  pkg/template/template_suite_test.go
  pkg/watch/watch_suite_test.go
  test/cmd/test-scenario/generator/generator_suite_test.go
  test/shell/funcs.go
  test/test_suite.tpl
Labels: dependencies

#819 fix: rename Dockerfile to Containerfile
  Makefile
  build/Containerfile
  build/ContainerfileTest
  build/ContainerfileTestPrepared
  build/bundle.Containerfile
Labels: internal/infra, kind/enhancement
