Repository maistra/istio-workspace, pull requests merged in 2021-01, with the labels that each got.

#599 doc: add service preview comparison doc
  docs/modules/ROOT/pages/comparisons/service_preview.adoc
Labels: component/docs

#602 feat: enables defining strategy templates in custom folder
  Makefile
  pkg/assets/assets_suite_test.go
  pkg/assets/isto-workspace-deploy.go
  pkg/assets/loader.go
  pkg/assets/loader_test.go
  pkg/cmd/config/env_vars.go
  pkg/cmd/install/install.go
  pkg/controller/session/session_controller.go
  pkg/controller/session/session_controller_int_test.go
  pkg/k8s/deployment.go
  pkg/k8s/deployment_test.go
  pkg/openshift/deploymentconfig.go
  pkg/openshift/deploymentconfig_test.go
  pkg/openshift/parser/template.go
  pkg/template/template.go
  pkg/template/template_test.go
  template/strategies/_basic-remove.tpl
  template/strategies/_basic-version.tpl
  template/strategies/prepared-image.tpl
  template/strategies/prepared-image.var
  template/strategies/telepresence.tpl
  template/strategies/telepresence.var
Labels: component/operator, kind/enhancement

#581 chore(make): removes obsolete targets
  Makefile
Labels: internal/infra, kind/enhancement, skip-changelog

#614 fix(e2e): ensure we check if there are deployments incase pods are no…
  deploy/operator.tpl.yaml
  e2e/error_path_test.go
  e2e/infra/pod_state.go
  e2e/operator_installation_test.go
  e2e/smoke_test.go
  pkg/assets/isto-workspace-deploy.go
  pkg/cmd/execute/cmd_test.go
  pkg/internal/session/session.go
  pkg/istio/virtualservice.go
  pkg/openshift/parser/template_test.go
  test/cmd/test-scenario/generator/generators.go
  test/shell/test_setup.go
Labels: internal/test-infra, kind/bug

#615 chore(label): add MVP label to group todo tasks for first product rel…
  .github/labels.yml
Labels: internal/infra, kind/enhancement

#638 fix(cli): print full url to image being used for install
  e2e/operator_installation_test.go
  pkg/cmd/install/cmd.go
Labels: MVP, component/cli, kind/bug
